# -*- coding: utf-8 -*-
"""final-project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d777mk6ogRDU9bvH4kqEl8PGdJN0KcnQ
"""

import random

vegetables = ['cucumber', 'ginger', 'garlic', 'radish', 'peas', 'pumpkin', 'onion' ]

fruits = ['peach', 'apple', 'banana', 'mango', 'cherry', 'apricot', 'banana',]

animals= ['gorilla', 'lion','cat','dog','rabbit', 'monkey','sheep', 'bear','elephant']

stationery= ['pencil','eraser','paper','glue','marker','colours','highlighter','glitterpens']

electronics=['television','computer','keyboard','mouse','lcd','microwave','wifi','fan','light']

colours=['red','blue','orange','green','voilet','purple','yellow','black','white','grey', 'golden','silver','brown','pink','skin']

# while 1:
#     word=vegetables+fruits+animals+stationery+electronics+colours

# random_word=random.choice(word)
# print("Word guessing game")

# if random_word in vegetables:
#     print("guess: word is related to animal")
# elif random_word in fruits:
#     print("guess:word is related to fruit")
# elif random_word in animals:
#     print("guess:word is related to animals")
# elif random_word in stationery:
#     print("guess:word is related to stationery")
# elif random_word in electronics:
#     print("guess:word is related to electronics")
# else : 
#     print("guess:word is related to colours")


# user_guess=''
# chances=20




# while chances >0:
#     wrong_guess=0
#     for ch in random_word:
#         if ch in user_guess:
#             print(ch, end =' ')
#         else:
#             wrong_guess+=1
#             print('_' ,end =' ')
#     if wrong_guess ==0:
#         print( 'you win the game',random_word)
#         again=print('you want to play again?, yes or no')
#         if again == 'Yes':
#             break
#         else:
#             quit()
#     guess=input('guess the word')
#     user_guess+=guess

#     if guess not in random_word:
#         chances-=1
#         print ("incorrect you have left {chances} chances")
#         if chances==0:
#             print('game over try again')
#             restart=input('do you want to play again , yes or no')
#             if restart =='No':
#                 quit()

              

# ------------------------------------





word=vegetables+fruits+animals+stationery+electronics+colours

random_word=random.choice(word)
print("Word guessing game")

if random_word in vegetables:
    print("guess: word is related to animal")
elif random_word in fruits:
    print("guess:word is related to fruit")
elif random_word in animals:
    print("guess:word is related to animals")
elif random_word in stationery:
    print("guess:word is related to stationery")
elif random_word in electronics:
    print("guess:word is related to electronics")
else : 
    print("guess:word is related to colours")


user_guess=''
chances=20




while chances >0:
    wrong_guess=0
    for ch in random_word:
        if ch in user_guess:
            print(ch, end =' ')
        else:
            wrong_guess+=1
            print('_' ,end =' ')
    if wrong_guess ==0:
        print( 'you win the game',random_word)
        break
    guess=input('guess the word')
    user_guess+=guess

    if guess not in random_word:
        chances-=1
        print (f"incorrect you have left {chances} chances")
        if chances==0:
            print('game over try again')